config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/twitter' => 'omniauth_callbacks#twitter'
  end

  resources :attachments, only: [:destroy]

  concern :votable do
    resources :votes, only: [:up, :down, :unvote] do
      post :up, on: :collection
      post :down, on: :collection
      post :unvote, on: :collection
    end
  end
  
  resources :questions, concerns: :votable do
    resources :comments, only: [:create]
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: [:create]
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get :search, to: 'search#index'
  

  root 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Attachable
  include Votable
  include Commentable
  
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, as: :votable
  has_many :subscriptions, dependent: :destroy

  validates :title, :body, :user_id, presence: true

  after_create :author_subscribe

  scope :created_for_day, -> { where(created_at: 1.day.ago..Time.zone.now) }

  def best_answer
    answers.where(best: true).first
  end

  private

  def author_subscribe
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource
  
  def index
    respond_with Question.all, each_serializer: QuestionsSerializer
  end

  def show
    respond_with Question.find(params[:id])
  end

  def create
    respond_with current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: [:show]
  before_action :set_subscription, only: [:show]
  after_action :publish_question, only: [:create]

  respond_to :json, :js

  authorize_resource
  
  def index
    respond_with (@questions = Question.all)
  end

  def show    
    respond_with @question 
  end

  def new
    respond_with(@question = Question.new) 
  end

  def edit    
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    respond_with(@question.update(question_params))
  end

  def destroy
    respond_with(@question.destroy)
  end

  private
    def load_question
      @question = Question.find(params[:id])
    end

    def build_answer
      @answer = @question.answers.build
    end

    def set_subscription
      @subscription = @question.subscriptions.find_by(user: current_user)
    end

    def publish_question
      PrivatePub.publish_to('/questions', question: @question.to_json) if @question.valid?
    end

    def question_params
      params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_delete])
    end
end

app/views/questions/_form.html.slim
= form_for @question do |f|
  
  = f.label :title
  br
  = f.text_field :title, class: "form-control", placeholder: "Заголовок"
  br
  = f.label :body
  br
  = f.text_area :body, class: "form-control", placeholder: "Вопрос"
  br

  p Attachment:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = render 'attachments/attachments_fields', f: a
      = link_to_add_association 'Добавить', f, :attachments, partial: 'attachments/attachments_fields'

  = f.submit 'Создать', class: 'btn btn-info active'

app/views/questions/_question.html.slim
.question id = "question-#{@question.id}"
  .content
    h2 = @question.title
    p = @question.body
    = render partial: 'votes/vote', locals: {votable: @question, type: "question"}

    p Attachment
    ul
      - @question.attachments.each do |a|
        li id="attachment-id-#{a.id}"
          = link_to a.file.identifier, a.file.url
          - if can?(:destroy, a)
            br
            = link_to 'удалить', attachment_path(a), method: :delete, remote: true

    br

    - if can?(:crud, @question)
      = link_to 'Редактировать', '', class: 'edit_question_link'
      = link_to 'Удалить', question_path, method: :delete

  .comments
    - @question.comments.each do |c|
      = render partial: 'comments/comment', locals: {comment: c}
    = link_to 'Add comment','', class: 'create-comment-link', data: { commentable_id: @question.id }
    
    = form_for [ @question, @question.comments.build ], method: "post", remote: true, html: { id: "create-comment-#{@question.id}"} do |f|
      = f.label :comment_body, "Comment"
      = f.text_area :comment_body
      = f.submit 'Create'


  .subscription
    - if can?(:destroy, @subscription)
      = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, remote: true
    - else
      = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, remote: true      

  .edit_question_show
    = form_for @question, remote: true do |f|
      = f.label :title, 'Заголовок'
      = f.text_field :title, class: "form-control"
      br
      = f.label :body, 'Ваш вопрос'
      = f.text_area :body, class: "form-control"
      br
      = f.submit 'Save', class: 'btn btn-info active'  

app/views/questions/edit.html.slim
h3.text-center Редакция

= render 'form'

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  h3.text-center Вопросы
  .questions
    - @questions.each do |q|
      p = q.title
      = link_to 'Показать', question_path(q)
      - if user_signed_in? && current_user.id == q.user_id
          p = link_to 'Удалить', question_path(q), method: :delete

  = subscribe_to "/questions"

app/views/questions/new.html.slim
h3.text-center Задайте вопрос

= render 'form'

app/views/questions/show.html.slim
= render @question

h3 Ответы

.answers
  = render @question.answers
  
.new-answer
  = form_for [@question, @answer], remote: true do |f| 
    p= f.label :body, 'Ответ'
    .answer-errors
      p= f.text_area :body 
      p= f.fields_for :attachments, @answer.attachments.build do |a|
        = render 'attachments/attachments_fields', f: a
        = link_to_add_association 'Добавить', f, :attachments, partial: 'attachments/attachments_fields'
      p= f.submit 'Создать'

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
    $('.question').replaceWith('<%= j render @question %>');
    $('.edit_question_show').hide()
<% end %>