config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/twitter' => 'omniauth_callbacks#twitter'
  end

  resources :attachments, only: [:destroy]

  concern :votable do
    resources :votes, only: [:up, :down, :unvote] do
      post :up, on: :collection
      post :down, on: :collection
      post :unvote, on: :collection
    end
  end
  
  resources :questions, concerns: :votable do
    resources :comments, only: [:create]
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: [:create]
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get :search, to: 'search#index'
  

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Attachable
  include Votable
  include Commentable
  
  belongs_to :user
  belongs_to :question, touch: true
  has_many :votes, as: :votable
  
  validates :body, :question_id, :user_id, presence: true

  after_create :notify_subscribers

  default_scope { order(best: :desc) }

  def set_best
    Answer.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  def notify_subscribers
    NotifySubscribersJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: [:create]
  before_action :set_answer, only: [:update, :destroy, :best]

  respond_to :js

  authorize_resource

  def new
    @answer = Answer.new
    respond_with @answer
  end

  def show    
  end

  def create
    respond_with (@answer = @question.answers.create(answer_params.merge({ user: current_user })))
  end

  def update      
    respond_with(@answer.update(answer_params))  
  end

  def destroy   
    respond_with(@answer.destroy)
  end

  def best
    @answer.set_best #if current_user.author_of?(@question)
    @answers = @answer.question.answers
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
      @question = @answer.question
    end

    def load_question
      @question = Question.find(params[:question_id])
    end

    def answer_params
      params.require(:answer).permit(:body, :best, attachments_attributes: [:file, :id, :_delete])
    end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def index
    @question = Question.find(params[:question_id])
    respond_with @question.answers
  end

  def show 
    @answer = Answer.find(params[:id])
    respond_with @answer, serializer: AnswerSerializer
  end

  def create
    @question = Question.find(params[:question_id])
    respond_with @question.answers.create(answer_params.merge(user: current_resource_owner))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
- cache answer do
  .answ id = "answer-#{answer.id}"
    - if answer.persisted?
      div class="answer-#{answer.id}" class=('best-answer' if answer.best?)
        p= answer.body
        = render partial: 'votes/vote', locals: {votable: answer, type: "answer"}
        br
        ul
          - answer.attachments.each do |a|
            li id="attachment-id-#{a.id}"
              = link_to a.file.identifier, a.file.url
              - if can?(:manage, a)
                br
                = link_to 'удалитьфайл', attachment_path(a), method: :delete, remote: true     
                       
        - if user_signed_in? && current_user.author_of?(answer)     
          =link_to 'УдалитьОтвет', answer, method: :delete, remote: true
          br
          =link_to 'Редактировать', '', class: 'edit-answer-link', data: { answer_id: answer.id }
          p
            =form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
              p=f.label :body, 'редакция'
              .answer-errors
              p=f.text_area :body
              p=f.submit 'Сохранить' 

          - if answer.best?
            b= 'Этот ответ лучший'
          - else can?(:best, answer)
            = link_to 'Лучший ответ', best_answer_path(answer), method: :patch, remote: true

        .comments
          - answer.comments.each do |c|
            = render partial: 'comments/comment', locals: {comment: c}
          = link_to 'коммент','', class: 'create-comment-link', data: { commentable_id: answer.id }
          = form_for [ answer, answer.comments.build ], method: "post", remote: true, html: { id: "create-comment-#{answer.id}"} do |f|
            = f.label :comment_body, "Комментарий"
            = f.text_area :comment_body
            = f.submit 'Create'
              

app/views/answers/_new.html.slim
h3 Ответы
- @question.answers.each do |answer| 
  p = answer.body 
  - if user_signed_in? && current_user.id == answer.user_id
      = link_to 'Удалить', answer, method: :delete

h4 Просто добавь ответ:

= form_for([@question, @question.answers.build]) do |f| 
  
  p= f.label :body
  p= f.text_area :body 

  p = f.submit 'Создать'

app/views/answers/best.js.erb
$('.answers').html('<%= j render @answers %>');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% publish_to "/questions/#{@question.id}/answers" do %>
    $('.answers').append('<%= j render @answer %>');
  <% end %>
  
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/delete.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
      $('.answer-errors').html('<%= j message %>');
<% end %>
<% else %>
      $('<%= ".answer-#{@answer.id}" %>').fadeOut();
      $('.flash').replaceWith('<%= j render 'layouts/flash' %>');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
      $('.answer-errors').html('<%= j message %>');
<% end %>
<% else %>
      $('.answer-<%= @answer.id %>').fadeOut(); 
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $( '.answer-' + <%= @answer.id %> ).html('<%= j render @answer %>');
    $('.edit-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      answer_id = $(this).data('answerId');
      $('form#edit-answer-' + answer_id).show();
    });
<% end %>