config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/twitter' => 'omniauth_callbacks#twitter'
  end

  resources :attachments, only: [:destroy]

  concern :votable do
    resources :votes, only: [:up, :down, :unvote] do
      post :up, on: :collection
      post :down, on: :collection
      post :unvote, on: :collection
    end
  end
  
  resources :questions, concerns: :votable do
    resources :comments, only: [:create]
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, only: [:create]
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  get :search, to: 'search#index'
  

  root 'questions#index'

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Qna"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Qna
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Вопросы", root_path
              li= link_to 'Новый', new_question_path
              li= link_to "Link 3", "/path3"
            ul.nav.navbar-nav.navbar-right
              li= link_to "Выход", destroy_user_session_path, method: :delete
              li= link_to "Вход", new_user_session_path
              li= link_to "Регистрация", new_user_registration_path

    .container
      .row
        .col-lg-9
          / = notice 
          / = alert 
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li = form_tag("/search", method: "get") do
                = label_tag :query, ""
                = text_field_tag :query, params[:query]
                = select_tag(:condition, options_for_select(Search::CONDITIONS, params[:condition]))
                = submit_tag "Search"

      footer
        p &copy; Company 2016